### ISSUE TITLE
Server side Handler simplifications

### ISSUE THREAD

**Issue by Pancia** [untangled-web/untangled-server#16]
- Make sure there's an api function to handle a request, so you can use w/e stack you want
- Integrate more reasonable default ring middleware
- WIP: will add more once i remember xD

**Comment by awkay** [comment]
So, I know you're working on middleware plugins, but we'll still need prehook and posthook middleware. Here is the use-case:

In ring-defaults, I'll need to set the session store. I cannot set that in advance because I'll want the store to be a dependency in a component (which will not exist yet). So, ring defaults, as a result, will need to be a component that depends upon an optional session store component (when present, it adds it during `start`).

Other pure function middleware won't need this, but things like session support will.

**Comment by Pancia** [comment]
https://github.com/untangled-web/untangled-server/pull/18
